global using AutoFactAI;
global using AutoFactCore.Interfaces;
global using AutoFactMail.Interfaces;
global using AutoFactOCR;
global using AutoFactCore.UseCases;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Configuration;
global using AutoFactConfiguration;